version: '3.9'

services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    volumes:
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
      - ./initdb/:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
